name: "makimono-action"
description: "Update the release notes with your latest change."
author: "Andreas Geyer <andreas@qbitone.de>"

branding:
  icon: "edit"
  color: "blue"

runs:
  using: "node24"
  main: "dist/index.js"
